apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-master
  namespace: bot
spec:
  template:
    spec:
      containers:
        - imagePullPolicy: Always
          name: container-0
      imagePullSecrets:
