version: '3.2'

services:
  php:
    build:
      dockerfile: docker/development/php/Dockerfile
      context: ./
    volumes:
      - ./app/:/web/app
    working_dir: /web/app/
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: "serverName=Docker"
    env_file:
      - .env
    ports:
      - "9001:9001"
