version: '3.9'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./docker/development/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./app/:/web/app
    ports:
      - "${NGINX_PORT}:80"
    links:
      - php
  php:
    restart: unless-stopped
    build:
      dockerfile: docker/development/php/Dockerfile
      context: ./
    volumes:
      - ./app/:/web/app
    working_dir: /web/app/
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: "serverName=Docker"
    env_file:
      - .env
    ports:
      - "${XDEBUG_PORT}:9001"
  postgres:
    image: postgres:11
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgresdata:/data/postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      TZ: "Europe/Moscow"
    platform: 'linux/amd64'
volumes:
  postgresdata:
