<?php

namespace Tests\Unit;

use Arslav\Bot\App;
use Arslav\Bot\DoctrineRunner;
use Codeception\Stub\Expected;
use Codeception\Test\Unit;
use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManager;
use Exception;
use Psr\Container\ContainerInterface;

class DoctrineRunnerTest extends Unit
{

    private ContainerInterface $container;

    /**
     * @throws Exception
     */
    protected function setUp(): void
    {
        $this->container = App::getContainer();
        $this->container->set('migration', [
            'namespace' => 'Arslav/Bot',
            'src' => 'src/Migrations'
        ]);
        $this->container->set(
            EntityManager::class,
            $this->makeEmpty(EntityManager::class)
        );
        $this->container->set(
            Connection::class,
            $this->makeEmpty(Connection::class)
        );
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     *
     * @throws Exception
     */
    public function testRun(): void
    {
        $doctrine = $this->construct(
            DoctrineRunner::class,
            [$this->container],
            ['run' => Expected::once()]
        );
        $doctrine->run();
    }
}
