name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login registry
      uses: docker/login-action@v2
      with:
        registry: registry.knaaru.ru
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: registry.knaaru.ru/bot:latest, registry.knaaru.ru/bot:${{ github.sha }}
    - name: Run tests
    - uses: addnab/docker-run-action@v3
      with: 
        image: registry.knaaru.ru/bot:latest
        run: vendor/bin/codecept run
