name: Build & Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: registry.knaaru.ru/bot:latest, registry.knaaru.ru/bot:${{ github.sha }}
    - name: Composer Install & Run Tests
      uses: addnab/docker-run-action@v3
      with: 
        image: registry.knaaru.ru/bot:latest
        run: |
          composer install --no-interaction
          vendor/bin/codecept run
